# Site settings
title: GoEcosystem
description: A comprehensive ecosystem of Go applications, libraries, and tools
baseurl: ""
url: "https://goecosystem.github.io"
repository: GoEcosystem/GoEcosystem.github.io

# Build settings
markdown: kramdown
highlighter: rouge

# Jekyll settings
permalink: pretty
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/GoEcosystem/GoEcosystem.github.io
  repository_name: GoEcosystem.github.io
  owner_name: GoEcosystem
  owner_url: https://github.com/GoEcosystem

# Theme and plugins
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-github-metadata

# Link rendering
relative_links:
  enabled: true
  collections: true

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "api"
    values:
      layout: "api"
  - scope:
      path: "guides"
    values:
      layout: "guide"
  - scope:
      path: "reference"
    values:
      layout: "reference"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Repositories
    url: /#repositories
  - title: Documentation
    url: /#documentation
  - title: GitHub
    url: https://github.com/GoEcosystem
